"""add payment_terms and tracking_number to orders

Revision ID: 69498322f5a9
Revises: 0002_add_cancelled
Create Date: 2026-05-19 16:38:01.708062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69498322f5a9'
down_revision: Union[str, None] = '0002_add_cancelled'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_terms', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tracking_number')
    op.drop_column('orders', 'payment_terms')
    # ### end Alembic commands ###
